name: Automated
favicon: null
layout_spectrum: 0.650984859559685
typography_spectrum: 0.4699035796802491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.29290708783082664
  saturation: 0.3568619687575847
  rhythmicContrast: 0.26689834194257855
purpose: []
