name: Automated
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4699035796802491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#940c1c'
    - '#304130'
    - '#cd7f67'
    - '#beb67e'
  brandStrength: 0.5
  lightness: 0.29290708783082664
  saturation: 0.3568619687575847
  rhythmicContrast: 0.26689834194257855
purpose: []
